'use client'

import Link from 'next/link'
import { AlertTriangle, BarChart3, Calendar, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Eye, FileText, Play, Plus, Send, Sparkles, Video } from 'lucide-react'
import { useLanguage } from '@/theme/i18n'
import { Card, CardHeader } from '@/components/ui/card'
import { KpiCard, type KpiTone } from '@/components/ui/kpi-card'
import { PipelineStatus } from '@/components/ui/pipeline-status'
import { StatusBadge } from '@/components/ui/status-badge'
import { mockAgendaToday, mockCostSummary, mockDashboardKpis, mockPerformance7d, mockPipelineCounts, mockRecentActivity, mockRecentContent } from '@/mocks/dashboard-mocks'

const kpis: Array<{ key: keyof typeof mockDashboardKpis; label: string; description: string; tone: KpiTone; icon: React.ReactNode }> = [
  { key: 'videosToday', label: 'Videos Generados Hoy', description: 'Objetivo diario', tone: 'primary', icon: <Play className="h-5 w-5" /> },
  { key: 'pendingReview', label: 'Pendientes de revisión', description: 'Necesitan revisión', tone: 'warning', icon: <FileText className="h-5 w-5" /> },
  { key: 'approved', label: 'Aprobados', description: 'Listos para programar', tone: 'success', icon: <CheckCircle2 className="h-5 w-5" /> },
  { key: 'scheduledToday', label: 'Programados', description: 'Para publicar hoy', tone: 'info', icon: <Calendar className="h-5 w-5" /> },
  { key: 'publishedToday', label: 'Publicados', description: 'Hoy', tone: 'primary', icon: <Send className="h-5 w-5" /> },
  { key: 'errors', label: 'Errores', description: 'Requieren atención', tone: 'error', icon: <AlertTriangle className="h-5 w-5" /> },
]

export function Dashboard() {
  const { t } = useLanguage()
  const labelMap: Record<string, string> = Object.fromEntries(['DRAFT', 'GENERATING', 'VALIDATING', 'RENDERING', 'REVIEW', 'APPROVED', 'SCHEDULED', 'PUBLISHED'].map((status) => [`dashboard.status${status}`, t(`dashboard.status${status}`)]))
  const totalViews = mockPerformance7d.reduce((sum, item) => sum + item.views, 0)
  const maxViews = Math.max(...mockPerformance7d.map((item) => item.views))

  return <div className="dashboard-canvas p-4 md:p-6 max-w-[1600px] mx-auto">
    <section className="grid grid-cols-2 md:grid-cols-3 2xl:grid-cols-6 gap-3 mb-4">
      {kpis.map((item) => <KpiCard key={item.key} label={item.label} value={item.key === 'videosToday' ? `${mockDashboardKpis.videosToday} / ${mockDashboardKpis.dailyTarget}` : mockDashboardKpis[item.key]} description={item.description} tone={item.tone} icon={item.icon} progress={item.key === 'videosToday' ? 100 : undefined} />)}
    </section>

    <section className="grid grid-cols-1 2xl:grid-cols-12 gap-4 mb-4">
      <Card className="2xl:col-span-5 min-h-[258px]"><CardHeader title="Pipeline de Producción" /><PipelineStatus counts={mockPipelineCounts} labels={labelMap} /></Card>
      <Card className="2xl:col-span-4 min-h-[258px]"><CardHeader title="Costo Estimado" /><div className="mb-3 flex gap-4 text-xs text-textSecondary"><span className="flex items-center gap-1"><i className="h-2 w-2 rounded-full bg-primary" />Costo diario</span><span className="flex items-center gap-1"><i className="h-2 w-2 rounded-full bg-success" />Costo mensual</span></div><div className="relative h-32 border-b border-border"><svg viewBox="0 0 100 50" preserveAspectRatio="none" className="h-full w-[74%] overflow-visible"><polyline points="0,44 15,30 30,26 45,19 60,13 75,8 100,6" fill="none" stroke="rgb(var(--color-success))" strokeWidth="1.4" vectorEffect="non-scaling-stroke" /><polyline points="0,43 15,41 30,42 45,40 60,41 75,38 100,39" fill="none" stroke="rgb(var(--color-primary))" strokeWidth="1.4" vectorEffect="non-scaling-stroke" /></svg><div className="absolute right-0 top-1 text-right"><p className="text-xs text-textSecondary">Hoy</p><p className="text-xl font-bold text-primary">${mockCostSummary.todayUsd.toFixed(2)}</p><p className="mt-5 text-xs text-textSecondary">Este mes</p><p className="text-xl font-bold text-success">${mockCostSummary.monthUsd.toFixed(2)}</p></div></div><div className="mt-2 flex justify-between text-[11px] text-textSecondary"><span>12 May</span><span>14 May</span><span>16 May</span><span>18 May</span></div></Card>
      <Card className="2xl:col-span-3 min-h-[258px]"><CardHeader title="Agenda de Hoy" action={<Link href="/calendar" className="text-xs text-primary hover:underline">Ver calendario</Link>} /><ul>{mockAgendaToday.map((item) => <li key={item.time} className="flex items-center gap-2 border-b border-border py-2 last:border-0"><Clock3 className="h-3.5 w-3.5 text-textSecondary" /><time className="w-14 text-[11px] text-textSecondary">{item.time}</time><p className="min-w-0 flex-1 truncate text-xs font-medium text-textPrimary">{item.title}</p><StatusBadge tone="scheduled">{t(item.typeKey)}</StatusBadge></li>)}</ul><Link href="/calendar" className="mt-3 flex justify-center gap-1 text-xs text-primary">Ver agenda completa <ChevronRight className="h-3.5 w-3.5" /></Link></Card>
    </section>

    <section className="grid grid-cols-1 2xl:grid-cols-12 gap-4">
      <Card padded={false} className="2xl:col-span-5 overflow-hidden"><div className="p-4 pb-2"><CardHeader title="Contenido Reciente" /></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-y border-border bg-surface-secondary text-left text-[11px] text-textSecondary"><tr><th className="px-4 py-2 font-medium">Título</th><th className="px-2 py-2 font-medium">Tipo</th><th className="px-2 py-2 font-medium">Estado</th><th className="px-3 py-2 font-medium">Programado</th></tr></thead><tbody>{mockRecentContent.map((item) => <tr key={item.id} className="border-b border-border last:border-0 hover:bg-surface-secondary/70"><td className="px-4 py-3 font-medium text-textPrimary">{item.title}<span className="block text-xs font-normal text-textSecondary">Contenido listo para publicar</span></td><td className="px-2 py-3 text-xs text-textSecondary">{t(item.typeKey)}</td><td className="px-2 py-3"><StatusBadge tone={item.statusTone}>{t(item.statusLabelKey)}</StatusBadge></td><td className="px-3 py-3 text-xs text-textSecondary">{item.scheduledAt}</td></tr>)}</tbody></table></div><Link href="/videos" className="flex items-center justify-center gap-1 p-3 text-xs font-medium text-primary">Ver todos los videos <ChevronRight className="h-3.5 w-3.5" /></Link></Card>
      <div className="2xl:col-span-4 space-y-4"><Card><CardHeader title="Rendimiento (7 días)" action={<span className="rounded-md border border-border px-2 py-1 text-[10px] text-textSecondary">Últimos 7 días</span>} /><div className="grid grid-cols-5 gap-2">{[['Vistas', `${(totalViews / 1000).toFixed(1)}K`], ['Me gusta', '2.1K'], ['Comentarios', '312'], ['Compartidos', '784'], ['Retención', '68%']].map(([label, value]) => <div key={label} className="rounded-lg border border-border p-2"><p className="text-[10px] text-textSecondary">{label}</p><p className="mt-1 font-bold text-textPrimary">{value}</p><p className="text-[10px] text-success">↑ 12.5%</p></div>)}</div><div className="mt-4 flex h-24 items-end gap-2">{mockPerformance7d.map((point) => <div key={point.dayKey} className="flex flex-1 flex-col items-center gap-1"><div className="w-full rounded-t bg-primary/85" style={{ height: `${(point.views / maxViews) * 100}%` }} /><span className="text-[10px] text-textSecondary">{t(point.dayKey)}</span></div>)}</div></Card><Card><CardHeader title="Accesos Rápidos" /><nav className="grid grid-cols-5 gap-2">{[[Plus,'Generar','/content/generate'],[Video,'Videos','/videos'],[Eye,'Revisiones','/review'],[Calendar,'Calendario','/calendar'],[BarChart3,'Analíticas','/analytics']].map(([Icon,label,href]) => { const IconComponent = Icon as typeof Plus; return <Link key={label as string} href={href as string} className="flex flex-col items-center gap-1 rounded-lg p-2 hover:bg-primary/10"><span className="rounded-lg bg-primary/10 p-2 text-primary"><IconComponent className="h-4 w-4" /></span><span className="text-[10px] text-textSecondary">{label as string}</span></Link>})}</nav></Card></div>
      <div className="2xl:col-span-3 space-y-4"><Card><CardHeader title="Actividad Reciente" action={<Link href="/notifications" className="text-xs text-primary">Ver todas</Link>} /><ul>{mockRecentActivity.map((item) => <li key={item.id} className="flex gap-2 border-b border-border py-2 last:border-0"><span className="mt-0.5 rounded-full bg-primary/10 p-1.5 text-primary"><Sparkles className="h-3.5 w-3.5" /></span><div className="min-w-0"><p className="text-xs font-medium text-textPrimary">{t(item.eventKey)}</p><p className="truncate text-[11px] text-textSecondary">{item.detail}</p><p className="text-[10px] text-textSecondary">{t(item.relativeTimeKey)}</p></div></li>)}</ul></Card><Card><CardHeader title="Notificaciones" action={<Link href="/notifications" className="text-xs text-primary">Ver todas</Link>} /><div className="flex gap-3"><span className="rounded-full bg-primary/10 p-3 text-primary"><CircleDollarSign className="h-5 w-5" /></span><div><p className="text-sm font-medium text-textPrimary">Tienes 3 videos pendientes de revisión</p><p className="text-xs text-textSecondary">Revísalos y aprueba su programación.</p><p className="mt-1 text-[10px] text-textSecondary">Hace 5 minutos</p></div></div></Card></div>
    </section>
  </div>
}
